// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.mockito.Mockito;
import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class DefaultMutableAccountData_getEmail_7b79ef55db_Test {

    private DefaultMutableAccountData defaultMutableAccountData;

    @BeforeMethod
    public void setUp() {
        defaultMutableAccountData = Mockito.mock(DefaultMutableAccountData.class);
    }

    @Test
    public void testGetEmailSuccess() {
        String expectedEmail = "test@example.com";
        Mockito.when(defaultMutableAccountData.getEmail()).thenReturn(expectedEmail);

        String actualEmail = defaultMutableAccountData.getEmail();

        Assert.assertEquals(actualEmail, expectedEmail, "Emails should match");
    }

    @Test
    public void testGetEmailFailure() {
        String expectedEmail = "test@example.com";
        Mockito.when(defaultMutableAccountData.getEmail()).thenReturn(null);

        String actualEmail = defaultMutableAccountData.getEmail();

        Assert.assertNotEquals(actualEmail, expectedEmail, "Emails should not match");
    }
}
