// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.testng.annotations.Test;
import org.testng.Assert;
import org.mockito.Mockito;

public class DefaultMutableAccountData_setExternalKey_3b661476ab_Test {

    @Test
    public void testSetExternalKey() {
        // Create a mock object
        DefaultMutableAccountData mockAccountData = Mockito.mock(DefaultMutableAccountData.class);

        // Define return value for method setExternalKey()
        String externalKey = "testKey";
        Mockito.doAnswer(invocation -> {
            Object arg0 = invocation.getArgument(0);
            Assert.assertEquals(arg0, externalKey);
            return null;
        }).when(mockAccountData).setExternalKey(Mockito.anyString());

        // Call method under test
        mockAccountData.setExternalKey(externalKey);
    }

    @Test
    public void testSetExternalKeyNull() {
        // Create a mock object
        DefaultMutableAccountData mockAccountData = Mockito.mock(DefaultMutableAccountData.class);

        // Define return value for method setExternalKey()
        Mockito.doAnswer(invocation -> {
            Object arg0 = invocation.getArgument(0);
            Assert.assertNull(arg0);
            return null;
        }).when(mockAccountData).setExternalKey(Mockito.anyString());

        // Call method under test with null argument
        mockAccountData.setExternalKey(null);
    }
}
