// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.mockito.Mockito;
import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;


public class DefaultMutableAccountData_setEmail_1aa52c5ba3_Test {

    private DefaultMutableAccountData defaultMutableAccountData;

    @BeforeMethod
    public void setUp() {
        defaultMutableAccountData = Mockito.mock(DefaultMutableAccountData.class);
    }

    @Test
    public void testSetEmailSuccess() {
        String email = "test@example.com";

        Mockito.doAnswer(invocation -> {
            Object arg0 = invocation.getArgument(0);
            Assert.assertEquals(email, arg0);
            return null;
        }).when(defaultMutableAccountData).setEmail(email);

        defaultMutableAccountData.setEmail(email);
    }

    @Test(expectedExceptions = NullPointerException.class)
    public void testSetEmailNull() {
        String email = null;

        Mockito.doAnswer(invocation -> {
            Object arg0 = invocation.getArgument(0);
            Assert.assertNull(arg0);
            return null;
        }).when(defaultMutableAccountData).setEmail(email);

        defaultMutableAccountData.setEmail(email);
    }
}
