// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.testng.annotations.Test;
import org.testng.Assert;
import org.mockito.Mockito;

public class DefaultMutableAccountData_setFirstNameLength_546cb00917_Test {

    @Test
    public void testSetFirstNameLength_PositiveValue() {
        // Mocking the DefaultMutableAccountData class
        DefaultMutableAccountData defaultMutableAccountData = Mockito.mock(DefaultMutableAccountData.class);
		
        // Call the method with positive value
        defaultMutableAccountData.setFirstNameLength(5);
		
        // Verify the method was called with correct parameter
        Mockito.verify(defaultMutableAccountData).setFirstNameLength(5);
    }
	
    @Test
    public void testSetFirstNameLength_NegativeValue() {
        // Mocking the DefaultMutableAccountData class
        DefaultMutableAccountData defaultMutableAccountData = Mockito.mock(DefaultMutableAccountData.class);
		
        // Call the method with negative value
        defaultMutableAccountData.setFirstNameLength(-5);
		
        // Verify the method was called with correct parameter
        Mockito.verify(defaultMutableAccountData).setFirstNameLength(-5);
    }
	
    @Test(expectedExceptions = Exception.class)
    public void testSetFirstNameLength_InvalidValue() {
        // Mocking the DefaultMutableAccountData class
        DefaultMutableAccountData defaultMutableAccountData = Mockito.mock(DefaultMutableAccountData.class);
		
        // Call the method with invalid value
        defaultMutableAccountData.setFirstNameLength(1000000); // TODO: Change this value as per your requirement
		
        // Verify the method was called with correct parameter
        Mockito.verify(defaultMutableAccountData).setFirstNameLength(1000000); // TODO: Change this value as per your requirement
    }
}
