// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.testng.annotations.Test;
import org.testng.Assert;
import org.mockito.Mockito;
import org.joda.time.DateTimeZone;

public class DefaultMutableAccountData_getTimeZone_bba9da3e8a_Test {
    
    @Test
    public void testGetTimeZoneSuccess() {
        DateTimeZone expectedTimeZone = DateTimeZone.UTC;
        
        DefaultMutableAccountData defaultMutableAccountData = Mockito.mock(DefaultMutableAccountData.class);
        Mockito.when(defaultMutableAccountData.getTimeZone()).thenReturn(expectedTimeZone);
        
        DateTimeZone actualTimeZone = defaultMutableAccountData.getTimeZone();
        
        Assert.assertEquals(actualTimeZone, expectedTimeZone, "Expected and actual Time Zones do not match");
    }
    
    @Test
    public void testGetTimeZoneFailure() {
        DateTimeZone expectedTimeZone = DateTimeZone.UTC;
        
        DefaultMutableAccountData defaultMutableAccountData = Mockito.mock(DefaultMutableAccountData.class);
        Mockito.when(defaultMutableAccountData.getTimeZone()).thenReturn(DateTimeZone.getDefault());
        
        DateTimeZone actualTimeZone = defaultMutableAccountData.getTimeZone();
        
        Assert.assertNotEquals(actualTimeZone, expectedTimeZone, "Expected and actual Time Zones should not match");
    }
}
