// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.mockito.Mockito;
import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class DefaultMutableAccountData_getFirstNameLength_ce2aea8c92_Test {
    private DefaultMutableAccountData defaultMutableAccountData;

    @BeforeMethod
    public void setUp() {
        defaultMutableAccountData = Mockito.mock(DefaultMutableAccountData.class);
    }

    @Test
    public void testGetFirstNameLength() {
        Mockito.when(defaultMutableAccountData.getFirstNameLength()).thenReturn(5);
        Integer length = defaultMutableAccountData.getFirstNameLength();
        Assert.assertEquals(length, Integer.valueOf(5));
    }

    @Test
    public void testGetFirstNameLength_Null() {
        Mockito.when(defaultMutableAccountData.getFirstNameLength()).thenReturn(null);
        Integer length = defaultMutableAccountData.getFirstNameLength();
        Assert.assertNull(length);
    }

    @Test
    public void testGetFirstNameLength_Zero() {
        Mockito.when(defaultMutableAccountData.getFirstNameLength()).thenReturn(0);
        Integer length = defaultMutableAccountData.getFirstNameLength();
        Assert.assertEquals(length, Integer.valueOf(0));
    }
}
