// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.testng.annotations.Test;
import org.testng.Assert;
import java.util.UUID;
import org.mockito.Mockito;

public class DefaultMutableAccountData_getPaymentMethodId_2a1e9171f3_Test {

    @Test
    public void testGetPaymentMethodIdSuccess() {
        DefaultMutableAccountData defaultMutableAccountData = Mockito.mock(DefaultMutableAccountData.class);
        UUID expectedPaymentMethodId = UUID.randomUUID();
        Mockito.when(defaultMutableAccountData.getPaymentMethodId()).thenReturn(expectedPaymentMethodId);
        UUID actualPaymentMethodId = defaultMutableAccountData.getPaymentMethodId();
        Assert.assertEquals(actualPaymentMethodId, expectedPaymentMethodId, "Expected and actual payment method id do not match");
    }

    @Test
    public void testGetPaymentMethodIdNull() {
        DefaultMutableAccountData defaultMutableAccountData = Mockito.mock(DefaultMutableAccountData.class);
        Mockito.when(defaultMutableAccountData.getPaymentMethodId()).thenReturn(null);
        UUID actualPaymentMethodId = defaultMutableAccountData.getPaymentMethodId();
        Assert.assertNull(actualPaymentMethodId, "Payment method id is not null");
    }
}
