// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.joda.time.DateTimeZone;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import static org.mockito.Mockito.*;
import static org.testng.Assert.*;

public class DefaultMutableAccountData_setTimeZone_9c63703f29_Test {

    private DefaultMutableAccountData defaultMutableAccountData;

    @BeforeMethod
    public void setup() {
        defaultMutableAccountData = mock(DefaultMutableAccountData.class);
    }

    @Test
    public void testSetTimeZone() {
        DateTimeZone timeZone = DateTimeZone.forID("Europe/London");
        doAnswer(invocation -> {
            DateTimeZone input = invocation.getArgument(0);
            assertEquals(input, timeZone);
            return null;
        }).when(defaultMutableAccountData).setTimeZone(any(DateTimeZone.class));

        defaultMutableAccountData.setTimeZone(timeZone);
    }

    @Test(expectedExceptions = IllegalArgumentException.class)
    public void testSetTimeZoneWithInvalidId() {
        DateTimeZone timeZone = DateTimeZone.forID("Invalid/Timezone");
        doThrow(new IllegalArgumentException()).when(defaultMutableAccountData).setTimeZone(timeZone);
        defaultMutableAccountData.setTimeZone(timeZone);
    }
}
