// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.testng.annotations.Test;
import org.mockito.Mockito;
import static org.testng.Assert.assertEquals;
import static org.mockito.Mockito.when;

public class DefaultAccountService_getName_8400ac6fb7_Test {

    @Test
    public void testGetNameSuccess() {
        // Mocking the KILLBILL_SERVICES
        KILLBILL_SERVICES mockServices = Mockito.mock(KILLBILL_SERVICES.class);
        when(mockServices.ACCOUNT_SERVICE.getServiceName()).thenReturn("AccountService");

        // TODO: Inject the mockServices into the instance of the class where getName() method is declared
        // Assuming the class is DefaultAccountService
        DefaultAccountService defaultAccountService = new DefaultAccountService(mockServices);
        String serviceName = defaultAccountService.getName();

        assertEquals(serviceName, "AccountService", "Service name should be AccountService");
    }

    @Test
    public void testGetNameFailure() {
        // Mocking the KILLBILL_SERVICES
        KILLBILL_SERVICES mockServices = Mockito.mock(KILLBILL_SERVICES.class);
        when(mockServices.ACCOUNT_SERVICE.getServiceName()).thenReturn(null);

        // TODO: Inject the mockServices into the instance of the class where getName() method is declared
        // Assuming the class is DefaultAccountService
        DefaultAccountService defaultAccountService = new DefaultAccountService(mockServices);
        String serviceName = defaultAccountService.getName();

        assertEquals(serviceName, null, "Service name should be null");
    }
}
