// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.testng.annotations.Test;
import org.mockito.Mockito;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.testng.Assert.assertEquals;

public class DefaultMutableAccountData_setName_3abba3fbc9_Test {

    @Test
    public void testSetName_Success() {
        DefaultMutableAccountData defaultMutableAccountData = mock(DefaultMutableAccountData.class);
        String expectedName = "Test Name";
        defaultMutableAccountData.setName(expectedName);
        verify(defaultMutableAccountData, times(1)).setName(expectedName);
    }

    @Test
    public void testSetName_Null() {
        DefaultMutableAccountData defaultMutableAccountData = mock(DefaultMutableAccountData.class);
        String expectedName = null;
        defaultMutableAccountData.setName(expectedName);
        verify(defaultMutableAccountData, times(1)).setName(expectedName);
    }

    @Test(expectedExceptions = IllegalArgumentException.class)
    public void testSetName_IllegalArgument() {
        DefaultMutableAccountData defaultMutableAccountData = mock(DefaultMutableAccountData.class);
        String expectedName = "";
        defaultMutableAccountData.setName(expectedName);
        verify(defaultMutableAccountData, times(1)).setName(expectedName);
    }
}
