// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.testng.annotations.Test;
import org.mockito.Mockito;
import static org.testng.Assert.assertEquals;
import static org.mockito.Mockito.when;

public class DefaultMutableAccountData_getBillCycleDayLocal_1ac6d90012_Test {

    @Test
    public void testGetBillCycleDayLocalSuccess() {
        DefaultMutableAccountData defaultMutableAccountData = Mockito.mock(DefaultMutableAccountData.class);
        when(defaultMutableAccountData.getBillCycleDayLocal()).thenReturn(15);

        int result = defaultMutableAccountData.getBillCycleDayLocal();
        assertEquals(result, 15);
    }

    @Test
    public void testGetBillCycleDayLocalFailure() {
        DefaultMutableAccountData defaultMutableAccountData = Mockito.mock(DefaultMutableAccountData.class);
        when(defaultMutableAccountData.getBillCycleDayLocal()).thenReturn(null);

        Integer result = defaultMutableAccountData.getBillCycleDayLocal();
        assertEquals(result, null);
    }
}
