// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import org.killbill.billing.catalog.api.Currency;
import org.mockito.Mockito;

public class DefaultMutableAccountData_setCurrency_abd5ac136c_Test {

    private DefaultMutableAccountData defaultMutableAccountData;

    @BeforeMethod
    public void setUp() {
        defaultMutableAccountData = new DefaultMutableAccountData();
    }

    @Test
    public void testSetCurrencySuccess() {
        Currency currency = Mockito.mock(Currency.class);
        defaultMutableAccountData.setCurrency(currency);
        Assert.assertEquals(defaultMutableAccountData.getCurrency(), currency, "Currency not set correctly");
    }

    @Test
    public void testSetCurrencyNull() {
        defaultMutableAccountData.setCurrency(null);
        Assert.assertNull(defaultMutableAccountData.getCurrency(), "Currency should be null");
    }
}
