// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import java.util.UUID;
import org.testng.Assert;
import org.testng.annotations.Test;
import org.mockito.Mockito;

public class DefaultMutableAccountData_setPaymentMethodId_88a0fde1d8_Test {

    @Test
    public void testSetPaymentMethodId_validUUID() {
        DefaultMutableAccountData accountData = Mockito.mock(DefaultMutableAccountData.class);
        UUID paymentMethodId = UUID.randomUUID();

        accountData.setPaymentMethodId(paymentMethodId);

        Mockito.verify(accountData, Mockito.times(1)).setPaymentMethodId(paymentMethodId);
        Assert.assertEquals(accountData.getPaymentMethodId(), paymentMethodId);
    }

    @Test
    public void testSetPaymentMethodId_nullUUID() {
        DefaultMutableAccountData accountData = Mockito.mock(DefaultMutableAccountData.class);

        accountData.setPaymentMethodId(null);

        Mockito.verify(accountData, Mockito.times(1)).setPaymentMethodId(null);
        Assert.assertNull(accountData.getPaymentMethodId());
    }
}
