// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import static org.mockito.Mockito.when;
import static org.testng.Assert.assertEquals;

public class DefaultAccountService_getRegistrationOrdering_27aaba7ae3_Test {

    @Mock
    private KILLBILL_SERVICES killbillServices;

    @BeforeMethod
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetRegistrationOrdering_ValidOrdering() {
        when(killbillServices.ACCOUNT_SERVICE.getRegistrationOrdering()).thenReturn(1);
        int ordering = killbillServices.ACCOUNT_SERVICE.getRegistrationOrdering();
        assertEquals(ordering, 1, "Expected registration ordering: 1");
    }

    @Test
    public void testGetRegistrationOrdering_InvalidOrdering() {
        when(killbillServices.ACCOUNT_SERVICE.getRegistrationOrdering()).thenReturn(-1);
        int ordering = killbillServices.ACCOUNT_SERVICE.getRegistrationOrdering();
        assertEquals(ordering, -1, "Expected registration ordering: -1");
    }
}
