// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.testng.annotations.Test;
import org.mockito.Mockito;
import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertNull;

public class DefaultMutableAccountData_getLocale_5e3e7f8eb8_Test {

    @Test
    public void testGetLocale() {
        DefaultMutableAccountData defaultMutableAccountData = Mockito.mock(DefaultMutableAccountData.class);
        Mockito.when(defaultMutableAccountData.getLocale()).thenReturn("en_US");
        String locale = defaultMutableAccountData.getLocale();
        assertEquals(locale, "en_US");
    }

    @Test
    public void testGetLocale_Null() {
        DefaultMutableAccountData defaultMutableAccountData = Mockito.mock(DefaultMutableAccountData.class);
        Mockito.when(defaultMutableAccountData.getLocale()).thenReturn(null);
        String locale = defaultMutableAccountData.getLocale();
        assertNull(locale);
    }
}
