// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.testng.annotations.Test;
import org.mockito.Mockito;
import static org.testng.Assert.assertEquals;

public class DefaultMutableAccountData_setBillCycleDayLocal_c91f49d751_Test {

    @Test
    public void testSetBillCycleDayLocalPositive() {
        DefaultMutableAccountData defaultMutableAccountData = new DefaultMutableAccountData();
        int billCycleDayLocal = 15;
        defaultMutableAccountData.setBillCycleDayLocal(billCycleDayLocal);
        assertEquals(defaultMutableAccountData.getBillCycleDayLocal(), billCycleDayLocal);
    }

    @Test
    public void testSetBillCycleDayLocalNegative() {
        DefaultMutableAccountData defaultMutableAccountData = new DefaultMutableAccountData();
        int billCycleDayLocal = -5;
        defaultMutableAccountData.setBillCycleDayLocal(billCycleDayLocal);
        assertEquals(defaultMutableAccountData.getBillCycleDayLocal(), billCycleDayLocal);
    }
}
