// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.killbill.billing.catalog.api.Currency;

import static org.mockito.Mockito.when;

public class DefaultMutableAccountData_getCurrency_963f35b794_Test {

    @Mock
    private DefaultMutableAccountData defaultMutableAccountData;

    @BeforeClass
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetCurrency_success() {
        when(defaultMutableAccountData.getCurrency()).thenReturn(Currency.USD);

        Currency result = defaultMutableAccountData.getCurrency();

        Assert.assertNotNull(result);
        Assert.assertEquals(result, Currency.USD);
    }

    @Test
    public void testGetCurrency_null() {
        when(defaultMutableAccountData.getCurrency()).thenReturn(null);

        Currency result = defaultMutableAccountData.getCurrency();

        Assert.assertNull(result);
    }
}
