// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.joda.time.DateTime;
import org.joda.time.DateTimeZone;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.mockito.Mockito.when;
import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertNotNull;

public class DefaultMutableAccountData_getReferenceTime_9b98d85467_Test {

    @Mock
    private DefaultMutableAccountData defaultMutableAccountData;

    @BeforeMethod
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetReferenceTime_ValidTime() {
        DateTime expectedTime = new DateTime(DateTimeZone.UTC);
        when(defaultMutableAccountData.getReferenceTime()).thenReturn(expectedTime);

        DateTime actualTime = defaultMutableAccountData.getReferenceTime();
        assertNotNull(actualTime);
        assertEquals(actualTime, expectedTime);
    }

    @Test
    public void testGetReferenceTime_NullTime() {
        when(defaultMutableAccountData.getReferenceTime()).thenReturn(null);

        DateTime actualTime = defaultMutableAccountData.getReferenceTime();
        assertEquals(actualTime, null);
    }
}
