// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.mockito.Mockito;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

public class DefaultMutableAccountData_getName_8400ac6fb7_Test {

    private DefaultMutableAccountData defaultMutableAccountData;

    @BeforeClass
    public void setUp() {
        defaultMutableAccountData = Mockito.mock(DefaultMutableAccountData.class);
    }

    @Test
    public void testGetName_Success() {
        String expectedName = "John Doe";
        Mockito.when(defaultMutableAccountData.getName()).thenReturn(expectedName);
        String actualName = defaultMutableAccountData.getName();
        Assert.assertEquals(actualName, expectedName, "Names do not match");
    }

    @Test
    public void testGetName_Null() {
        Mockito.when(defaultMutableAccountData.getName()).thenReturn(null);
        String actualName = defaultMutableAccountData.getName();
        Assert.assertNull(actualName, "Name should be null");
    }
}
