// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import org.mockito.Mockito;

public class DefaultMutableAccountData_getExternalKey_ab5c8d68ee_Test {

    private DefaultMutableAccountData defaultMutableAccountData;

    @BeforeMethod
    public void setUp() {
        defaultMutableAccountData = Mockito.mock(DefaultMutableAccountData.class);
    }

    @Test
    public void testGetExternalKey_Success() {
        String expectedKey = UUID.randomUUID().toString();
        Mockito.when(defaultMutableAccountData.getExternalKey()).thenReturn(expectedKey);

        String actualKey = defaultMutableAccountData.getExternalKey();
        Assert.assertEquals(actualKey, expectedKey);
    }

    @Test
    public void testGetExternalKey_Null() {
        Mockito.when(defaultMutableAccountData.getExternalKey()).thenReturn(null);

        String actualKey = defaultMutableAccountData.getExternalKey();
        Assert.assertNull(actualKey);
    }
}
