// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package org.killbill.billing.account.api;

import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import org.mockito.Mockito;

public class DefaultMutableAccountData_setLocale_0b31647fb2_Test {

    private DefaultMutableAccountData defaultMutableAccountData;

    @BeforeMethod
    public void setUp() {
        defaultMutableAccountData = Mockito.mock(DefaultMutableAccountData.class);
    }

    @Test
    public void testSetLocaleSuccess() {
        String testLocale = "en_US";
        Mockito.doAnswer(invocation -> {
            Object arg0 = invocation.getArgument(0);
            Assert.assertEquals(arg0, testLocale);
            return null;
        }).when(defaultMutableAccountData).setLocale(Mockito.anyString());

        defaultMutableAccountData.setLocale(testLocale);
    }

    @Test
    public void testSetLocaleFailure() {
        String testLocale = "en_US";
        Mockito.doAnswer(invocation -> {
            Object arg0 = invocation.getArgument(0);
            Assert.assertNotEquals(arg0, "fr_FR");
            return null;
        }).when(defaultMutableAccountData).setLocale(Mockito.anyString());

        defaultMutableAccountData.setLocale(testLocale);
    }
}
